# **NUMPY**

-   NumPy (Numerical Python) is a powerful Python library for numerical
     computing.
-  It provides support for large, multi-dimensional arrays and matrices,along
  with a collection of high-level mathematical functions to operate on these arrays.


-  **Arrays**:
-  NumPy's primary data structure is the ndarray (N-dimensional array).
-  It allows you to efficiently store and manipulate large amounts of numerical data.


In [8]:
!pip install numpy

In [9]:
import numpy as np

In [8]:
# creating a array
x = np.array([1,3,5])
y = np.array([[1,3,5],[7,9,11]])
z = np.array([[[(1,3,5,7)],[(9,11,13,17)],[(19,23,29,31)]]])


In [12]:
print(x)

[1 3 5]


In [13]:
print(y)

[[ 1  3  5]
 [ 7  9 11]]


In [14]:
print(z)

[[[[ 1  3  5  7]]

  [[ 9 11 13 17]]

  [[19 23 29 31]]]]


In [ ]:
# INTIAL PLACE HOLDER :

In [12]:
np.zeros([1,2,3])  # syntax : shape,row col

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# to create a array with ones

In [16]:
np.ones([1,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
# create an array evenly spaced values (step value)

In [26]:
x = np.arange(1,15,2)  #start value,end value,steps # n-1(3-1=2)
print(x)

[ 1  3  5  7  9 11 13]


In [28]:
y = np.arange(10,100,10)
print(y)

[10 20 30 40 50 60 70 80 90]


In [30]:
z = np.arange(20,30,0.7)
print(z)

[20.  20.7 21.4 22.1 22.8 23.5 24.2 24.9 25.6 26.3 27.  27.7 28.4 29.1
 29.8]


In [33]:
# create an array of evenly spaced values

a = np.linspace(10,100,20)
print(a)

[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]


In [34]:
b = np.linspace(5,50,2)
print(b)

[ 5. 50.]


In [36]:
c = np.linspace(7,75,10)
print(c)

[ 7.         14.55555556 22.11111111 29.66666667 37.22222222 44.77777778
 52.33333333 59.88888889 67.44444444 75.        ]


In [37]:
b = np.linspace(150,100,10)
print(b)

[150.         144.44444444 138.88888889 133.33333333 127.77777778
 122.22222222 116.66666667 111.11111111 105.55555556 100.        ]
